// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDfUGtN3GpuMJJvwrNRlmFL27CKo3id44',
    appId: '1:395215507973:android:f7a886b239d3154f0c826c',
    messagingSenderId: '395215507973',
    projectId: 'flutter-prep-3adc6',
    databaseURL: 'https://flutter-prep-3adc6-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-3adc6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyy3VZbkkFRCoxa9BhvNaL6iwKL6TjbrM',
    appId: '1:395215507973:ios:37fbab37410c96d40c826c',
    messagingSenderId: '395215507973',
    projectId: 'flutter-prep-3adc6',
    databaseURL: 'https://flutter-prep-3adc6-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-3adc6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
